### ISSUE TITLE
unknown type name ‘__poll_t’

### ISSUE THREAD

**Issue by Yu-jinyan** [enndubyu/ipmb_device#1]
Hello！
Linux kernel version 4.14.55 does not support '__poll_t'，How to solve it？

**Comment by enndubyu** [comment]
I'm on my phone right now, but I'll push a fix for this later this weekend. If you want to get unblocked in the meantime then you can just add something like this in the c file:

```c
#if (LINUX_VERSION_CODE < KERNEL_VERSION(4, 16, 0))
    typedef unsigned __poll_t;
#endif
```

**Comment by Yu-jinyan** [comment]
Okay, thank you very much!
This issue has been resolved, and my kernel version is 4.14.55.
When loading the module, I encountered the following problem again
```
# insmod ipmb_device.ko 
[ 1454.250006] ipmb_device: Unknown symbol i2c_slave_unregister (err 0)
[ 1454.256377] ipmb_device: disagrees about version of symbol i2c_register_driver
[ 1454.263658] ipmb_device: Unknown symbol i2c_register_driver (err -22)
[ 1454.270158] ipmb_device: Unknown symbol i2c_slave_register (err 0)
[ 1454.276373] ipmb_device: disagrees about version of symbol i2c_transfer
[ 1454.283023] ipmb_device: Unknown symbol i2c_transfer (err -22)
[ 1454.288849] ipmb_device: disagrees about version of symbol i2c_del_driver
[ 1454.295659] ipmb_device: Unknown symbol i2c_del_driver (err -22)
[ 1454.341960] ipmb_device: Unknown symbol i2c_slave_unregister (err 0)
[ 1454.348335] ipmb_device: disagrees about version of symbol i2c_register_driver
[ 1454.356059] ipmb_device: Unknown symbol i2c_register_driver (err -22)
[ 1454.362588] ipmb_device: Unknown symbol i2c_slave_register (err 0)
[ 1454.368799] ipmb_device: disagrees about version of symbol i2c_transfer
[ 1454.375430] ipmb_device: Unknown symbol i2c_transfer (err -22)
[ 1454.381288] ipmb_device: disagrees about version of symbol i2c_del_driver
[ 1454.388051] ipmb_device: Unknown symbol i2c_del_driver (err -22)
insmod: can't insert 'ipmb_device.ko': Invalid argument
```

**Comment by Yu-jinyan** [comment]
> I'm on my phone right now, but I'll push a fix for this later this weekend. If you want to get unblocked in the meantime then you can just add something like this in the c file:
> 
> ```c
> #if (LINUX_VERSION_CODE < KERNEL_VERSION(4, 16, 0))
>     typedef unsigned __poll_t;
> #endif
> ```

If you encounter the following problems
```
error: ‘EPOLLIN’ undeclared (first use in this function);
``` 
The following code needs to be added
```
#include <linux/eventpoll.h>
```

**Comment by enndubyu** [comment]
It looks like you built the module against a set of kernel headers that don't match the kernel that is currently running on your system. It could be a different version, or it could be the same version with a different config.

Did you check out a new kernel source tree to build against or did you already have headers available for the kernel you are running? If you had to rebuild with CONFIG_I2C_SLAVE, for example, before building the module, then you need to boot from that kernel in order to load the module.

**Comment by Yu-jinyan** [comment]
> It looks like you built the module against a set of kernel headers that don't match the kernel that is currently running on your system. It could be a different version, or it could be the same version with a different config.
> 
> Did you check out a new kernel source tree to build against or did you already have headers available for the kernel you are running? If you had to rebuild with CONFIG_I2C_SLAVE, for example, before building the module, then you need to boot from that kernel in order to load the module.

I compiled the entire kernel code as well as the module under ubuntu VM via cross compiler and then placed it on the embedded arm development board to load the module, `CONFIG_I2C_SLAVE` is configured but I have not updated the linux image on the SD card, at the moment I don't have a way to make an image,is it because of this reason, if so, I'll find a way to update the linux kernel image.

**Comment by enndubyu** [comment]
Yep, you probably need to replace the kernel in your image with the one you compiled. It seems like the kernel on your image wasn't built with CONFIG_I2C_SLAVE.

**Comment by Yu-jinyan** [comment]
> Yep, you probably need to replace the kernel in your image with the one you compiled. It seems like the kernel on your image wasn't built with CONFIG_I2C_SLAVE.

Ok, after replacing the kernel image, I successfully installed the driver module.
But I did not add the IPMB node in the device tree, how do I instantiate Ipmb-device in linux after manually loading the module in Linux.
My actions are as follows, ipmb-device cannot be instantiated
```
# echo ipmb-device 0x10 > /sys/bus/i2c/devices/i2c-1/new_device
[  771.461040] ipmb-device 1-0010: i2c_slave_register: client slave flag not set. You might see address collisions
[  771.473284] ipmb-device 1-0010: i2c_slave_register: not supported by adapter
[  771.480787] ipmb-device: probe of 1-0010 failed with error -95
[  771.486710] i2c i2c-1: new_device: Instantiated device ipmb-device at 0x10
```
My device tree is configured as follows by default, with two I2C nodes configured
```
  i2c0: i2c@e0002000 {
	  #address-cells = <1>;
	  #size-cells = <0>;
	  compatible = "snps,designware-i2c";
	  reg = <0xe0002000 0x1000>;
	  clocks = <&clk_uart>;
	  // clock-frequency = <400000>;
	  interrupts = <GIC_SPI 21 IRQ_TYPE_LEVEL_HIGH>;
	  status = "okay";
  };
  
  i2c1: i2c@e0022000 {
	  #address-cells = <1>;
	  #size-cells = <0>;
	  compatible = "snps,designware-i2c";
	  reg = <0xe0022000 0x1000>;
	  clocks = <&clk_uart>;
	  // clock-frequency = <400000>;
	  interrupts = <GIC_SPI 42 IRQ_TYPE_LEVEL_HIGH>;
	  status = "okay";
	  eeprom@50 {
		  compatible = "atmel,24c256";
		  reg = <0x50>;
	  };
  };
```

**Comment by Yu-jinyan** [comment]
> Yep, you probably need to replace the kernel in your image with the one you compiled. It seems like the kernel on your image wasn't built with CONFIG_I2C_SLAVE.

Ok, after replacing the kernel image, I successfully installed the driver module.
But I did not add the IPMB node in the device tree, how do I instantiate Ipmb-device in linux after manually loading the module in Linux.
My actions are as follows, ipmb-device cannot be instantiated
```
# echo ipmb-device 0x10 > /sys/bus/i2c/devices/i2c-1/new_device
[  771.461040] ipmb-device 1-0010: i2c_slave_register: client slave flag not set. You might see address collisions
[  771.473284] ipmb-device 1-0010: i2c_slave_register: not supported by adapter
[  771.480787] ipmb-device: probe of 1-0010 failed with error -95
[  771.486710] i2c i2c-1: new_device: Instantiated device ipmb-device at 0x10
```
我的设备树节默认配置如下，配置了两个I2C节点
```
  i2c0: i2c@e0002000 {
	  #address-cells = <1>;
	  #size-cells = <0>;
	  compatible = "snps,designware-i2c";
	  reg = <0xe0002000 0x1000>;
	  clocks = <&clk_uart>;
	  // clock-frequency = <400000>;
	  interrupts = <GIC_SPI 21 IRQ_TYPE_LEVEL_HIGH>;
	  status = "okay";
  };
  
  i2c1: i2c@e0022000 {
	  #address-cells = <1>;
	  #size-cells = <0>;
	  compatible = "snps,designware-i2c";
	  reg = <0xe0022000 0x1000>;
	  clocks = <&clk_uart>;
	  // clock-frequency = <400000>;
	  interrupts = <GIC_SPI 42 IRQ_TYPE_LEVEL_HIGH>;
	  status = "okay";
	  eeprom@50 {
		  compatible = "atmel,24c256";
		  reg = <0x50>;
	  };
  };
```

**Comment by enndubyu** [comment]
It looks like you might not have enabled `CONFIG_I2C_DESIGNWARE_SLAVE`. Some bus drivers have their own config options for slave support that you need to enable in addition to the high level slave support, and a cursory glance suggests that DesignWare driver is one of those.

One other thing to keep in mind is that when you are using `/sys/bus/i2c/devices/i2c-n/new_device` to register a slave driver, then you need to add 0x1000 to the i2c address so that linux can distinguish it from a master address. So if you use 0x1010 when registering the slave driver with `new_device`, then i2c slave requests to address 0x10 will be handled by that driver. You have to do something similar when adding slave drivers via the device tree, as you can see in the example dts in this repo.

**Comment by Yu-jinyan** [comment]
Hello, I found your driver only registered from the mode, then how to send data

**Comment by enndubyu** [comment]
Fixed in master
