### ISSUE TITLE
There is no IPMB-n node under the "/dev" path

### ISSUE THREAD

**Issue by Yu-jinyan** [enndubyu/ipmb_device#2]
When I compile the ipmb driver into the kernel
My compilation configuration is:
```
CONFIG_IPMB_DEVICE=y
CONFIG_I2C_SLAVE=y
```
My DTS file is as follows:
```
  i2c@e0002000 {
	  compatible = "snps,designware-i2c";
	  reg = <0xe0002000 0x1000>;
	  #address-cells = <0x1>;
	  #size-cells = <0x0>;
	  clocks = <0x1 0x2e>;
	  interrupts = <0x0 0x15 0x4>;
	  i2c-max-frequency = <0xf4240>;
	  status = "okay";
  
	  ipmb-device@1010 {
		  compatible = "ipmb-device";
		  #address-cells = <0x1>;
		  #size-cells = <0x0>;
			  reg = <(I2C_OWN_SLAVE_ADDRESS | 0x10)>;
	  };
  };
  
  i2c@e0022000 {
	  compatible = "snps,designware-i2c";
	  reg = <0xe0022000 0x1000>;
	  clocks = <0x1 0x2f>;
	  interrupts = <0x0 0x2a 0x4>;
	  #address-cells = <0x1>;
	  #size-cells = <0x0>;
	  i2c-max-frequency = <0xf4240>;
	  status = "okay";
  };
```

**Comment by Yu-jinyan** [comment]
When I compile the ipmb driver into a module
Load module as follows
```
# insmod ipmb_device.ko
```
The following devices can be seen in the "/dev" directory
```
i2c-0
i2c-1
ipmb-0
```
But it doesn't work, manipulating ipmb-0 via the write() function fails to send the message
My compilation configuration is:
```
CONFIG_IPMB_DEVICE=y
CONFIG_I2C_SLAVE=y
```
My DTS file is as follows:
```
  i2c@e0002000 {
	  compatible = "snps,designware-i2c";
	  reg = <0xe0002000 0x1000>;
	  #address-cells = <0x1>;
	  #size-cells = <0x0>;
	  clocks = <0x1 0x2e>;
	  interrupts = <0x0 0x15 0x4>;
	  i2c-max-frequency = <0xf4240>;
	  status = "okay";
  
	  ipmb-device@1010 {
		  compatible = "ipmb-device";
		  #address-cells = <0x1>;
		  #size-cells = <0x0>;
			  reg = <(I2C_OWN_SLAVE_ADDRESS | 0x10)>;
	  };
  };
  
  i2c@e0022000 {
	  compatible = "snps,designware-i2c";
	  reg = <0xe0022000 0x1000>;
	  clocks = <0x1 0x2f>;
	  interrupts = <0x0 0x2a 0x4>;
	  #address-cells = <0x1>;
	  #size-cells = <0x0>;
	  i2c-max-frequency = <0xf4240>;
	  status = "okay";
  };
```

**Comment by enndubyu** [comment]
Just to confirm, do you have `CONFIG_I2C_DESIGNWARE_SLAVE` and does the driver load without any errors in `dmesg`?

If you are having trouble with write() it could be a couple of things. Are you getting a positive return value from write()? If not, what is the value of `errno` after the write? 

Is there another device on the i2c bus with the correct address to receive the message? If the other device doesn't ACK the address byte, then the driver will abort by default. You can use the ioctl() interface to override this behavior, which might be useful for debugging. 

One thing to keep in mind is that the IPMB address and I2C address are slightly different due to the master write being included in what the IPMB spec calls the IPMB address. You need to shift the i2c address left by one to get the IPMB address, like in the example.

Another possiblity is that the IPMB header checksum in the message you are trying to write is invalid. If this is the case, then errno would be set to `EINVAL` and write() would return -1.

**Comment by enndubyu** [comment]
Also, make sure your are building the kennel without CONFIG_IPMB_DEVICE_INTERFACE.

**Comment by Yu-jinyan** [comment]
> Also, make sure your are building the kennel without CONFIG_IPMB_DEVICE_INTERFACE.

Yes, I used 4.14.55 and the kernel, There is no CONFIG _ IPMB _ DEVICE _ INTERFACE option

**Comment by Yu-jinyan** [comment]
> Just to confirm, do you have `CONFIG_I2C_DESIGNWARE_SLAVE` and does the driver load without any errors in `dmesg`?
> 
> If you are having trouble with write() it could be a couple of things. Are you getting a positive return value from write()? If not, what is the value of `errno` after the write?
> 
> Is there another device on the i2c bus with the correct address to receive the message? If the other device doesn't ACK the address byte, then the driver will abort by default. You can use the ioctl() interface to override this behavior, which might be useful for debugging.
> 
> One thing to keep in mind is that the IPMB address and I2C address are slightly different due to the master write being included in what the IPMB spec calls the IPMB address. You need to shift the i2c address left by one to get the IPMB address, like in the example.
> 
> Another possiblity is that the IPMB header checksum in the message you are trying to write is invalid. If this is the case, then errno would be set to `EINVAL` and write() would return -1.

Not available for ` ipmb_ Checksum_ Implementation of compute() `
The dmesg is as follows
```
# dmesg | grep ipmb
[    0.376752] i2c i2c-0: of_i2c: invalid addr=1010 on /amba@0/i2c@e0002000/ipmb-device@1010
[    0.376771] i2c i2c-0: Failed to create I2C device for /amba@0/i2c@e0002000/ipmb-device@1010
```

**Comment by enndubyu** [comment]
You will need to write a function to compute the checksum as described in the IPMB spec from Intel. 

My example is only intended to demonstrate basic usage of the driver. Any user interested in the driver is expected to already know how to build valid IPMB messages.

**Comment by enndubyu** [comment]
> ```
> # dmesg | grep ipmb
> [    0.376752] i2c i2c-0: of_i2c: invalid addr=1010 on /amba@0/i2c@e0002000/ipmb-device@1010
> [    0.376771] i2c i2c-0: Failed to create I2C device for /amba@0/i2c@e0002000/ipmb-device@1010
> ```
This is a device tree issue of some sort. When you are using the device tree, you don't want to add 0x1000 to the address, just or with I2C_OWN_SLAVE_ADDRESS. If you have 2 clients using the same address it could also cause this.
