### ISSUE TITLE
write failed: Operation not supported

### ISSUE THREAD

**Issue by Yu-jinyan** [enndubyu/ipmb_device#3]
There are no devices connected to my I2C bus, only pins left for connecting to other boards

* The user code is as follows,`write()` return -1
```c
int main(void){
        ...
        if (ioctl(ipmb_dev_fd, IPMB_IOC_EN_IGNORE_NACK, NULL) == -1)
	        perror("IGNORE_NACK mode not supported"); 
        
        ssize_t n = write(ipmb_dev_fd, cmd, 7);
        
        perror("----write failed");
        printf("----write returned %ld\n", n);
        ...
}
```
* The output is as follows:
```
----write failed: Operation not supported
----write returned -1
```
* I found that the`i2c_transfer()` function encountered an error during execution, why is this.
```
int i2c_transfer(struct i2c_adapter *adap, struct i2c_msg *msgs, int num)
{
	if (adap->algo->master_xfer) {
		...
	} else {
		dev_dbg(&adap->dev, "I2C level transfers not supported\n");
		return -EOPNOTSUPP;
	}
}
```
Open DEBUG
```
# dmesg | grep i2c
[    0.344331] i2c-core: driver [dummy] registered
[    0.374466] i2c-core: driver [stmpe-i2c] registered
[    0.376396] i2c i2c-0: adapter [Synopsys DesignWare I2C Slave adapter] registered
[    0.376673] i2c i2c-0: client [ipmb-device] registered with bus id 0-1010
[    0.377076] i2c i2c-1: adapter [Synopsys DesignWare I2C adapter] registered
[    1.241591] i2c-core: driver [at24] registered
[    1.516742] i2c-core: driver [rtc-ds1307] registered
[    1.516807] i2c-core: driver [rtc-pcf8563] registered
[    1.516817] i2c /dev entries driver
[    1.521114] i2c-core: driver [pca954x] registered
[   57.517553] i2c-core: driver [ipmb-device] registered
[   67.909147] i2c i2c-0: I2C level transfers not supported
```
* The configuration information is as follows:
```
CONFIG_IPMB_DEVICE=m
CONFIG_I2C_SLAVE=y

CONFIG_I2C_DESIGNWARE_CORE=y
CONFIG_I2C_DESIGNWARE_PLATFORM=y
CONFIG_I2C_DESIGNWARE_SLAVE=y
```
* The device tree is as follows:
```
i2c@e0002000 {
	compatible = "snps,designware-i2c";
	reg = <0xe0002000 0x1000>;
	#address-cells = <0x1>;
	#size-cells = <0x0>;
	clocks = <0x1 0x2e>;
	interrupts = <0x0 0x15 0x4>;
	i2c-max-frequency = <0xf4240>;
	status = "okay";
	ipmb-device@1010 {
		compatible = "ipmb-device";
		#address-cells = <0x1>;
		#size-cells = <0x0>;
		reg = <0x40000010>;
	};
};
```

**Comment by Yu-jinyan** [comment]
> There are no devices connected to my I2C bus, only pins left for connecting to other boards
> 
> * The user code is as follows,`write()` return -1
> 
> ```c
> int main(void){
>         ...
>         if (ioctl(ipmb_dev_fd, IPMB_IOC_EN_IGNORE_NACK, NULL) == -1)
> 	        perror("IGNORE_NACK mode not supported"); 
>         
>         ssize_t n = write(ipmb_dev_fd, cmd, 7);
>         
>         perror("----write failed");
>         printf("----write returned %ld\n", n);
>         ...
> }
> ```
> 
> * The output is as follows:
> 
> ```
> ----write failed: Operation not supported
> ----write returned -1
> ```
> 
> * I found that the`i2c_transfer()` function encountered an error during execution, why is this.
> 
> ```
> int i2c_transfer(struct i2c_adapter *adap, struct i2c_msg *msgs, int num)
> {
> 	if (adap->algo->master_xfer) {
> 		...
> 	} else {
> 		dev_dbg(&adap->dev, "I2C level transfers not supported\n");
> 		return -EOPNOTSUPP;
> 	}
> }
> ```
> 
> * The configuration information is as follows:
> 
> ```
> CONFIG_IPMB_DEVICE=m
> CONFIG_I2C_SLAVE=y
> 
> CONFIG_I2C_DESIGNWARE_CORE=y
> CONFIG_I2C_DESIGNWARE_PLATFORM=y
> CONFIG_I2C_DESIGNWARE_SLAVE=y
> ```
> 
> * The device tree is as follows:
> 
> ```
> i2c@e0002000 {
> 	compatible = "snps,designware-i2c";
> 	reg = <0xe0002000 0x1000>;
> 	#address-cells = <0x1>;
> 	#size-cells = <0x0>;
> 	clocks = <0x1 0x2e>;
> 	interrupts = <0x0 0x15 0x4>;
> 	i2c-max-frequency = <0xf4240>;
> 	status = "okay";
> 	ipmb-device@1010 {
> 		compatible = "ipmb-device";
> 		#address-cells = <0x1>;
> 		#size-cells = <0x0>;
> 		reg = <0x40000010>;
> 	};
> };
> ```
Open DEBUG
```
# dmesg | grep i2c
[    0.344331] i2c-core: driver [dummy] registered
[    0.374466] i2c-core: driver [stmpe-i2c] registered
[    0.376396] i2c i2c-0: adapter [Synopsys DesignWare I2C Slave adapter] registered
[    0.376673] i2c i2c-0: client [ipmb-device] registered with bus id 0-1010
[    0.377076] i2c i2c-1: adapter [Synopsys DesignWare I2C adapter] registered
[    1.241591] i2c-core: driver [at24] registered
[    1.516742] i2c-core: driver [rtc-ds1307] registered
[    1.516807] i2c-core: driver [rtc-pcf8563] registered
[    1.516817] i2c /dev entries driver
[    1.521114] i2c-core: driver [pca954x] registered
[   57.517553] i2c-core: driver [ipmb-device] registered
[   67.903133] ---------This is ipmb_i2c_write at line 170---------
[   67.909147] i2c i2c-0: I2C level transfers not supported
```

**Comment by enndubyu** [comment]
It looks like the DesignWare I2C driver doesn't support multimaster mode (where the i2c peripheral acts as both master and slave on the same bus). I don't have any experience with the DesignWare IP, but I can tell you how I'd approach this problem in a general way:

  1.  Make sure the DesignWare I2C controller supports multimaster mode in the first place. Some chips can't be configured for multimaster.

  2. If the i2c controller does support multimaster, then it might be worth checking if anyone added this functionality to the driver in a later version of Linux. If so, you may be able to backport it.

  3. If your I2C controller doesn't support, then you can look into hacks like using two I2C controllers connected to the same bus (one configured as master and the other configured as slave), bit-banging I2C, or even changing your SoC to one with better I2C support.

**Comment by Yu-jinyan** [comment]
> It looks like the DesignWare I2C driver doesn't support multimaster mode (where the i2c peripheral acts as both master and slave on the same bus). I don't have any experience with the DesignWare IP, but I can tell you how I'd approach this problem in a general way:
> 
> 1. Make sure the DesignWare I2C controller supports multimaster mode in the first place. Some chips can't be configured for multimaster.
> 2. If the i2c controller does support multimaster, then it might be worth checking if anyone added this functionality to the driver in a later version of Linux. If so, you may be able to backport it.
> 3. If your I2C controller doesn't support, then you can look into hacks like using two I2C controllers connected to the same bus (one configured as master and the other configured as slave), bit-banging I2C, or even changing your SoC to one with better I2C support.
Hello, my I2C controller does not support multimaster mode,
I want to know where the driver configures the I2C controller for multi-master mode

**Comment by enndubyu** [comment]
It's the responsibility of the bus driver to configure the controller to support the kernel's i2c interface. Initial configuration typically happens in the `probe()` callback, and configuration of the slave address and slave interrupts would usually be in the `reg_slave()` callback. You can look in `i2c-rcar.c` for an example that properly handles multimaster.
