### ISSUE TITLE
Master write fails and causes device to no longer recieve slave commands

### ISSUE THREAD

**Issue by aidancostello** [enndubyu/ipmb_device#5]
Hey! I'm attempting to implement a very bare bones VITA 46.11 chassis manager. I am only really interested in the "get sensor reading" command, where I would send a master write command to the peripheral asking for the data from a sensor. I would then receive a master write transaction from the peripheral with the sensor data encoded. I added a kernel module and set up the device tree like so:

```
&i2c0 {
	 ipmb-device@1010 {
        compatible = "ipmb-device";

        #address-cells = <1>;
        #size-cells = <0>;

        /* use slave address space for i2c client */
        reg = <(I2C_OWN_SLAVE_ADDRESS | 0x10)>;
    };
};
```

Here is the de-compiled device tree as well:

```
i2c@ff020000 {
	compatible = "cdns,i2c-r1p14\0cdns,i2c-r1p10";
	status = "okay";
	interrupt-parent = <0x04>;
	interrupts = <0x00 0x11 0x04>;
	reg = <0x00 0xff020000 0x00 0x1000>;
	#address-cells = <0x01>;
	#size-cells = <0x00>;
	power-domains = <0x0c 0x25>;
	clocks = <0x03 0x3d>;
	clock-frequency = <0x61a80>;

	ipmb-device@1010 {
		compatible = "ipmb-device";
		#address-cells = <0x01>;
		#size-cells = <0x00>;
		reg = <0x40000010>;
	};
};
```

The overarching i2c driver is I2C Cadence, which does support multi-master mode. The issue I was running into was that upon boot up, my board was able to receive system event log commands. The according data is placed into /dev/ipmb-0 successfully. However, once I attempt to master write to the peripheral, the write returns an error of -1. From then on, my board is unable to receive any master writes from the peripheral, and all transactions go NACK'd. If I attempt to write again after the first unsuccessful write, the full command is sent successfully, but I am still unable to ACK any master writes from the peripheral. Here is the basic user space code I was running. From what I can tell, the code was also hanging on the read() function, likely because there is no data in the read buffer.

```
int8_t cmd[8];
  cmd[0] = 0x20 << 1;                                        // Responder's Slave Address
  cmd[1] = (0x04 << 2) | (0x00);                             // Network function + LUN
  cmd[2] = calcChecksum(cmd[0] + cmd[1]);                    // Checksum 1
  cmd[3] = 0x18 << 1;                                        // Requester slave address
  cmd[4] = (0x01 << 2) | (0x00);                             // Request sequence + LUN
  cmd[5] = 0x2D;                                             // Command
  cmd[6] = 0x0A;                                             // Sensor number
  cmd[7] = calcChecksum(cmd[3] + cmd[4] + cmd[5] + cmd[6]);  // Checksum 2

  // open
  int ipmb_fd = open("/dev/ipmb-0", O_RDWR);

  // write command
  spdlog::info("bytes written: {}", write(ipmb_fd, cmd, 8));

  // read bytes
  uint8_t rsp[64];
  uint8_t num_read;
  num_read = read(ipmb_fd, rsp, 64);

  spdlog::info("bytes read: {}", num_read);

  // close
  close(ipmb_fd);
```

I would really appreciate any help/guidance you might have. Thanks!

**Comment by enndubyu** [comment]
What's the value of `errno` after the write returns -1? 

It looks like the requester slave address in your command doesn't match the slave address configured in the device tree, but I'd still expect the write to succeed as long as the other i2c controller is behaving.

Are you able to write the command using the `/dev/i2c1` device? 

Do you have a bus analyzer or something that you can use to verify that there are no abnormal conditions? 

Are there any errors from the i2c-cadence driver in `dmesg` output after you encounter the issue?

**Comment by aidancostello** [comment]
- `errno` returns a value of 6 after the write
- The requester address of `0x18` was left over from when I was experimenting with different addresses to see if it would fix the issue. Even with a requester address of `0x10`, the same issue occurs. 
- I am able to write the command with `/dev/i2c-0` but the same issue occurs where the first write fails
- I have a logic analyzer hooked up which confirms that no abnormal conditions are occurring
- There are no errors in `dmesg`

**Comment by aidancostello** [comment]
I was able to resolve the issue. The fix for me specifically was the clock frequency. The peripheral I am communicating with has a default clock frequency of 50 kHz instead of the usual 100 or 400. My zynq was able to first receive commands at 50 kHz, but once attempting to switch to 400 kHz to write a message, it would error. My suspicion is that in this error process, the bus was never switched back to 50 kHz, which is why it was never able to receive messages again. Locking the clock frequency at 50 kHz was the solution that worked. Here's my updated device tree for anyone that might have similar issues: 

```
&i2c0 {
	multi-master;
	status = "okay";
	clock-frequency = <50000>;

	ipmb-device@1018 {
        compatible = "ipmb-device";

        #address-cells = <1>;
        #size-cells = <0>;

        reg = <(I2C_OWN_SLAVE_ADDRESS | 0x18)>;
    };
};
```

This kernel module was very useful and saved me a lot of time, so thank you!

**Comment by enndubyu** [comment]
Glad you got it figured out! Thanks for the update.
